// SPDX-License-Identifier: AGPL-3.0-or-later
//
// THE CONTRACT, CHECKED FROM BOTH SIDES.
//
// 🔴 `fixtures/valid/tiny.expected.json` WAS WORKED BY HAND from the two files beside it, not produced by
// this reader. That is the whole point: a fixture generated by the implementation it checks proves only
// that the code agrees with itself, and the engine is going to write a SECOND reader against these files.
//
// So this suite is not really about `src/format/`. It is the same suite the engine's reader owes, run here
// first — and if these ever disagree with the code, a person decides which of the two was wrong.
import { describe, it, expect } from 'vitest';
import { readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { parseSet, recompose, type Palette, type VariantChoice } from '../src/format/semantic.ts';

const read = (...parts: string[]): string => readFileSync(join(process.cwd(), 'fixtures', ...parts), 'utf8');

interface ExpectedCase {
  readonly variants: VariantChoice;
  readonly pixels: readonly number[];
}

describe('fixtures/valid — what a reader must reproduce', () => {
  const set = parseSet(read('valid', 'tiny.semantic.json'));
  const palette = JSON.parse(read('valid', 'tiny.palette.json')) as Palette;
  const expected = JSON.parse(read('valid', 'tiny.expected.json')) as { sheet: string; cases: ExpectedCase[] };

  it('Right: the semantic file is accepted', () => {
    expect(set.sheets).toHaveLength(1);
    expect(set.sheets[0]!.width * set.sheets[0]!.height * 4).toBe(expected.cases[0]!.pixels.length);
  });

  for (const [i, one] of (JSON.parse(read('valid', 'tiny.expected.json')) as { cases: ExpectedCase[] }).cases.entries()) {
    const label = typeof one.variants === 'string' ? one.variants : 'per region';
    it(`🔴 case ${i + 1} — ${label}: every pixel matches the hand-worked expectation`, () => {
      expect([...recompose(set, expected.sheet, palette, one.variants)]).toEqual([...one.pixels]);
    });
  }

  it('🎯 Right: the shape is identical across every case — only the colours move', () => {
    const alpha = (pixels: readonly number[]): number[] =>
      pixels.filter((_, i) => i % 4 === 3).map((a) => (a === 0 ? 0 : 1));
    const shapes = expected.cases.map((c) => alpha(c.pixels).join(''));
    expect(new Set(shapes).size).toBe(1);
  });
});

describe('fixtures/invalid — what a reader must REFUSE', () => {
  const files = readdirSync(join(process.cwd(), 'fixtures', 'invalid')).filter((n) => n.endsWith('.json'));

  it('Right: there are files to refuse, so an empty folder cannot pass as success', () => {
    // Without this, deleting the fixtures would make the loop below vacuous and the suite would stay green
    // while checking nothing at all.
    expect(files.length).toBeGreaterThanOrEqual(5);
  });

  for (const name of files) {
    it(`🔴 refuses ${name}, and says something about what is wrong`, () => {
      let message = '';
      try {
        parseSet(read('invalid', name));
      } catch (error) {
        message = error instanceof Error ? error.message : String(error);
      }
      expect(message, `${name} was accepted`).not.toBe('');
      // ⚠️ «Invalid semantic file» sends a person back to a folder of hundreds with nothing to look for.
      expect(message.length).toBeGreaterThan(20);
    });
  }
});
